const fs=require('node:fs'),assert=require('node:assert/strict');
const api=new Function(fs.readFileSync('src/flow.js','utf8')+fs.readFileSync('src/engine.js','utf8')+';return {solveModel,makeGrid,solveFlow,parseSTL,stlContains};')();
const p={shape:'block',length:40,width:8,height:4,bore:6,n:6,rho:1e-4,k:120,alpha:0,density:3210,cp:750,contact:100,offsetA:0,offsetB:0,mode:'P',command:10,vmax:50,imax:30,pmax:100,ambient:25,sink:25,h:15,emissivity:0,hc:2000,maxTemp:2000,study:'steady',duration:.4,dt:.1,period:.4,duty:.5,initial:25,flow:true,channelWidth:20,channelHeight:10,gasDensity:1.2,gasCp:1005,gasK:.026,mu:1.8e-5,flowRate:5,gasInlet:25};
const checks=[];function check(name,fn){const values=fn();checks.push({name,pass:true,...values});console.log(name+': PASS',values);}
check('Square duct pressure drop converges toward analytical series',()=>{
 const errors=[];for(const n of [6,12]){const W=.01,L=.03,d=[W/n,W/n,L/(3*n)],m={nx:n,ny:n,nz:3*n,W,H:W,L,d,area:[d[1]*d[2],d[0]*d[2],d[0]*d[1]],vol:d[0]*d[1]*d[2],map:new Int32Array(n*n*3*n).fill(-1)};
 // Square-duct Poiseuille conductance from the converged odd-integer series.
 let sum=0;for(let k=1;k<1000;k+=2)sum+=Math.tanh(k*Math.PI/2)/k**5;const coefficient=(1-192/Math.PI**5*sum)/12;
 const r=api.solveFlow({...p,flowRate:1},m),exact=(1/6e7)*p.mu*L/(coefficient*W**4);errors.push(Math.abs(r.dp/exact-1));assert(r.massError<1e-5&&r.divergence<1e-6);}
 assert(errors[0]/errors[1]>3.2&&errors[1]<.04);return {relativeErrors:errors,errorReduction:errors[0]/errors[1]};
});
check('Coupled solid/gas power balance and outlet heating',()=>{const r=api.solveModel(p);assert(r.stats.energyError<1e-5);assert(r.gas.stats.outlet>p.gasInlet&&r.gas.stats.outlet<r.stats.max);assert(r.gas.stats.massError<1e-5);return {outlet_C:r.gas.stats.outlet,pressureDrop_Pa:r.gas.stats.dp,heatResidual:r.stats.energyError,massResidual:r.gas.stats.massError};});
check('Coupled transient accounts for solid and gas storage',()=>{const r=api.solveModel({...p,study:'transient'});assert(r.stats.integratedError<1e-4);return {input_J:r.stats.inputEnergy,stored_J:r.stats.stored,loss_J:r.stats.lossEnergy,residual:r.stats.integratedError};});
check('CSG subtraction removes a bore from a connected solid',()=>{const plain=api.makeGrid({...p,flow:false,width:10,height:10}),cad=api.makeGrid({...p,flow:false,width:10,height:10,shape:'cad',parts:[{type:'box',op:'union',width:10,height:10,length:40},{type:'cylinder',op:'subtract',diameter:4,length:40}]});assert(cad.N<plain.N&&cad.N>plain.N*.5);assert(cad.xyz.every(q=>Math.hypot(q[0],q[1])>.002));return {plainCells:plain.N,boredCells:cad.N};});
check('Closed ASCII STL imports and ray voxelization classify cube',()=>{const vertices=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]],faces=[[0,3,2,1],[4,5,6,7],[0,1,5,4],[3,7,6,2],[0,4,7,3],[1,2,6,5]];let stl='solid cube\n';for(const f of faces)for(const inds of [[0,1,2],[0,2,3]])stl+='facet normal 0 0 0\nouter loop\n'+inds.map(i=>'vertex '+vertices[f[i]].join(' ')).join('\n')+'\nendloop\nendfacet\n';stl+='endsolid cube';const bytes=new TextEncoder().encode(stl),parsed=api.parseSTL(bytes.buffer);assert(api.stlContains(parsed.triangles,0,.1,.2));assert(!api.stlContains(parsed.triangles,.6,.1,.2));const m=api.makeGrid({...p,flow:false,shape:'stl',triangles:parsed.triangles});assert(m.N===m.nx*m.ny*m.nz);assert.throws(()=>api.parseSTL(new TextEncoder().encode(stl.replace(/facet normal[\s\S]*?endfacet\n/,'')).buffer),/open|manifold/);return {triangles:parsed.triangles.length,cells:m.N};});
fs.writeFileSync('validation-flow.json',JSON.stringify(checks,null,2)+'\n');
