import fs from 'node:fs';import assert from 'node:assert/strict';import {Worker} from 'node:worker_threads';import {pathToFileURL} from 'node:url';
const solver=await import(pathToFileURL(process.cwd()+'/dist/suite/solver.js'));
const cfg={wallMaterial:'quartz',wallK:1.4,wallThickness:.003,wallEmissivity:.93,gap:.001,gapK:.03,endMode:'ambient',endK:1273.15,endH:200,contactRho:0,maxIter:160,tolerance:1e-4};
const material=solver.MATERIALS.find(m=>m.name==='SiC'),x={material,shape:'cylinder',solidFraction:1,volumeCm3:10,aspectRatio:3,imax:20,vmax:100,pmax:2000,ambientK:293.15,targetK:1273.15,emissivity:.8,convection:false,h:0,gasK:293.15,biLimit:.01,enclosure:cfg};
const url=pathToFileURL(process.cwd()+'/dist/suite/worker.js').href;
const w=new Worker(`const {parentPort}=require('node:worker_threads');global.self={postMessage:v=>parentPort.postMessage(v)};import(${JSON.stringify(url)}).then(()=>{parentPort.on('message',data=>self.onmessage({data}));parentPort.postMessage({ready:true});});`,{eval:true});
await new Promise((resolve,reject)=>{w.once('message',resolve);w.once('error',reject);});let id=0;const call=(type,args)=>new Promise((resolve,reject)=>{w.once('message',m=>m.error?reject(Error(m.error)):resolve(m.result));w.postMessage({id:++id,type,args});});
try{const expected=solver.calculate(x),zero=await call('zero',[x]);assert.equal(zero.tss,expected.tss);const direct=solver.solveThermal2D(x,expected,cfg,material),r=await call('steady',[x,zero,cfg,material]);assert(r.converged);assert.equal(r.avgK,direct.avgK);const mesh=solver.build2DMesh(r.g,r.cfg);assert.equal(mesh.nr,r.mesh.nr);assert.equal(mesh.materialAt(0,0),direct.mesh.materialAt(0,0));const plan={drive:'off',period:1,duty:.5,dt:.001,steps:2,duration:.002,startField:r.T,startK:x.ambientK,record:1};await call('start',[x,zero,cfg,material,plan]);await call('advance',[2]);const dynamic=await call('result',[]);assert.equal(dynamic.stepsDone,2);assert(dynamic.avgK<r.avgK);fs.writeFileSync('validation-unified.json',JSON.stringify({zeroD:zero.tss,thermal2D:r.avgK,workerMatchesDirect:true,transientSteps:dynamic.stepsDone},null,2));console.log('0D / 2D worker parity and transient execution passed');}finally{await w.terminate();}
for(const file of ['index.html','joule3d.html','suite/joule0d.html','suite/joule2d.html']){const html=fs.readFileSync('dist/'+file,'utf8');for(const m of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new Function(m[1].replace(/import\s*\{[\s\S]*?\}\s*from\s*"[^"]+";/g,''));}
assert(fs.readFileSync('dist/suite/joule0d.html','utf8').includes('data-dimension="0d"'));assert(fs.readFileSync('dist/suite/joule2d.html','utf8').includes('data-dimension="2d"'));console.log('All page scripts parse; dimensional settings namespaces are separate');
