const fs=require('node:fs'),assert=require('node:assert/strict');
const api=new Function(['flow','wall3d','engine'].map(n=>fs.readFileSync('src/'+n+'.js','utf8')).join('\n')+';return {solveModel,makeGrid,solveFlow,thermalWall3DNetwork,parseSTL,cg};')();
const p={shape:'block',length:30,width:4,height:2,n:6,nx:16,ny:16,nz:12,rho:1e-4,k:30,alpha:0,density:3210,cp:750,contact:100,offsetA:0,offsetB:0,mode:'P',command:3,vmax:50,imax:30,pmax:100,ambient:25,sink:25,h:15,emissivity:.8,hc:2000,maxTemp:2000,study:'steady',duration:.2,dt:.1,period:.2,duty:1,initial:25,flow:true,channelWidth:12,channelHeight:10,gasDensity:1.2,gasCp:1005,gasK:.026,mu:1.8e-5,flowRate:5,gasInlet:25,wall:true,wallGeometry:'cylinder3d',wallThickness:3,wallK:1.4,wallCp:730,wallDensity:2200,wallEmissivity:.8,insulationThickness:0,insulationK:.04};
const report=[];function check(name,fn){const values=fn();report.push({name,pass:true,...values});console.log(name,values);}
check('Cylindrical wall partitions heater, wall, gas and exterior',()=>{const m=api.makeGrid(p);let gas=0;for(let i=0;i<m.map.length;i++){assert(!(m.map[i]>=0&&m.wall3d.map[i]>=0));if(m.map[i]<0&&m.wall3d.map[i]<0&&!m.wall3d.outside[i])gas++;}assert(gas>0);const exact=Math.PI*(.009**2-.006**2)*.03,volume=m.wall3d.mesh.N*m.vol;assert(Math.abs(volume/exact-1)<.15);return {wallCells:m.wall3d.mesh.N,gasCells:gas,volume,exact};});
check('3D cylinder energy conservation and circumferential temperature variation',()=>{const r=api.solveModel(p);assert(r.stats.energyError<1e-5);assert(r.wall.stats.max>25);const mid=r.wall.mesh.ijk.reduce((a,q,i)=>{if(q[2]===6)a.push(r.wall.T[i]);return a;},[]);assert(Math.max(...mid)-Math.min(...mid)>.001);assert(r.gas.stats.massError<1e-5);return {energyResidual:r.stats.energyError,wallMax:r.wall.stats.max,crossSectionSpan:Math.max(...mid)-Math.min(...mid),massResidual:r.gas.stats.massError};});
check('Volumetric wall transient includes wall storage',()=>{const r=api.solveModel({...p,study:'transient'});assert(r.stats.integratedError<1e-4);return {input:r.stats.inputEnergy,stored:r.stats.stored,loss:r.stats.lossEnergy,residual:r.stats.integratedError};});
check('CSG wall and built-in rectangular shell give identical occupancy',()=>{const a=api.makeGrid({...p,wallGeometry:'box3d'}),b=api.makeGrid({...p,wallGeometry:'cad3d',wallWidth:18,wallHeight:16,wallParts:[{type:'box',op:'union',width:18,height:16,length:30},{type:'box',op:'subtract',width:12,height:10,length:32}]});assert.deepEqual(a.wall3d.map,b.wall3d.map);assert.deepEqual(a.wall3d.outside,b.wall3d.outside);return {cells:a.wall3d.mesh.N};});
check('Closed STL tube reproduces CSG wall occupancy',()=>{
 const outer=[[-9,-8],[9,-8],[9,8],[-9,8]],inner=[[-6,-5],[6,-5],[6,5],[-6,5]],v=[];for(const z of [-15,15])for(const q of [...outer,...inner])v.push([...q,z]);const faces=[];for(let i=0;i<4;i++){const j=(i+1)%4;faces.push([i,j,j+8,i+8],[i+4,i+12,j+12,j+4],[i,i+4,j+4,j],[i+8,j+8,j+12,i+12]);}let text='solid tube\n';for(const face of faces)for(const inds of [[0,1,2],[0,2,3]])text+='facet normal 0 0 0\nouter loop\n'+inds.map(i=>'vertex '+v[face[i]].join(' ')).join('\n')+'\nendloop\nendfacet\n';text+='endsolid tube';const parsed=api.parseSTL(new TextEncoder().encode(text).buffer),a=api.makeGrid({...p,wallGeometry:'box3d'}),b=api.makeGrid({...p,wallGeometry:'stl3d',wallWidth:18,wallHeight:16,wallTriangles:parsed.triangles});assert.deepEqual(a.wall3d.map,b.wall3d.map);return {triangles:parsed.triangles.length,cells:b.wall3d.mesh.N};
});
check('Radial wall conduction approaches the logarithmic cylinder solution',()=>{
 const errors=[];for(const n of [24,48]){const m=api.makeGrid({...p,nx:n,ny:n,nz:3}),w=m.wall3d.mesh,diag=new Float64Array(w.N),rhs=new Float64Array(w.N),conductances=w.edges.map(([a,b,axis])=>{const g=p.wallK*m.area[axis]/m.d[axis];diag[a]+=g;diag[b]+=g;return g;});
 for(const [list,target]of [[m.wall3d.innerFaces,100],[m.wall3d.outerFaces,25]])for(const [a,axis]of list)if(axis!==2){const g=2*p.wallK*m.area[axis]/m.d[axis];diag[a]+=g;rhs[a]+=g*target;}
 const t=api.cg(diag,w.edges,conductances,rhs);let error=0;w.xyz.forEach((q,i)=>{const exact=25+75*Math.log(.009/Math.hypot(q[0],q[1]))/Math.log(.009/.006);error+=(t[i]-exact)**2;});errors.push(Math.sqrt(error/w.N));}
 assert(errors[1]<errors[0]&&errors[1]<3);return {rmsErrorsC:errors};
});
check('Wall/element overlap is rejected',()=>{assert.throws(()=>api.makeGrid({...p,width:16,height:16}),/overlaps/);return {};});
fs.writeFileSync('validation-wall3d.json',JSON.stringify(report,null,2)+'\n');
