'use strict';
const $=id=>document.getElementById(id);
const keys=['meshType','nr','nt','initialMode','shape','length','width','height','bore','n','rho','k','alpha','density','cp','contact','offsetA','offsetB','mode','command','vmax','imax','pmax','ambient','sink','h','emissivity','hc','maxTemp','study','duration','dt','period','duty','initial','channelWidth','channelHeight','flowRate','gasInlet','mu','gasDensity','gasCp','gasK','wallThickness','wallK','wallCp','wallDensity','wallEmissivity','insulationThickness','insulationK','contactR','thermalR','slew','jlimit','limitAction','nx','ny','nz','targetLow','targetHigh','flowUnit','outletPressure','electrodeLength','electrodeRho','electrodeK','electrodeCp','electrodeDensity','wallGeometry','wallWidth','wallHeight'];
const strings=new Set(['meshType','initialMode','shape','mode','study','limitAction','flowUnit','wallGeometry']);

let cadParts=[],stlTriangles=null,wallParts=[],wallTriangles=null,viewModel;
let savedInitialState=null,lastCompletedState=null,solverWorker=null,previewKey=null,previewMesh=null;
function previewGrid(p){const key=geometryKey(p);if(previewMesh&&key===previewKey)return previewMesh;const mesh=makeGrid(p);previewKey=key;previewMesh=mesh;return mesh;}
let model,result=null,worker=null,yaw=.78,pitch=.38,zoom=1.3,drawn=[],drag=null,dirty=false;
const params=()=>({initialState:$('initialMode').value==='saved'?savedInitialState:null,...Object.fromEntries(keys.map(k=>[k,strings.has(k)?$(k).value:Number($(k).value)])),wall:$('wall').checked,rhoCurve:parseRhoTable(),...parseThermalTables(),materialSource:$('materialSource').value,materialPreset:$('material').value,flow:$('flow').checked,parts:cadParts,triangles:stlTriangles,wallParts,wallTriangles});
const fmt=(x,d=3)=>!Number.isFinite(x)?'—':Math.abs(x)!==0&&(Math.abs(x)<.001||Math.abs(x)>=1e5)?x.toExponential(2):x.toLocaleString('en-US',{maximumFractionDigits:d});
function status(s,error=false){$('status').textContent=s;$('status').classList.toggle('error',error);const top=$('topStatus');if(top){top.textContent=s;top.classList.toggle('error',error);}}
function controls(){const p=params();$('annularInputs').hidden=p.meshType!=='annular';$('heightrow').hidden=!['block','neck','cad','stl'].includes(p.shape);$('borerow').hidden=p.shape!=='tube';$('timeinputs').hidden=p.study!=='transient';$('contactval').textContent=p.contact+'%';$('flowinputs').hidden=!p.flow;$('h').disabled=p.flow&&!p.wall;$('emissivity').disabled=p.flow&&!p.wall;for(const o of $('field').options)if(['gasT','speed','pressure'].includes(o.value))o.disabled=!p.flow;for(const o of $('field').options)if(['wallT','wallGeometry','assembly'].includes(o.value))o.disabled=!wall3DEnabled(p);if(['wallT','wallGeometry','assembly'].includes($('field').value)&&!wall3DEnabled(p))$('field').value='T';$('commandlabel').firstChild.textContent='Setpoint ('+p.mode+')';}
let autoTimer=null;
function scheduleAutoSolve(){clearTimeout(autoTimer);if(worker||document.getElementById("workspace").hidden)return;autoTimer=setTimeout(()=>{if(document.getElementById("workspace").hidden||screeningIsRunning())return;run();},800);}
function invalidate(){
  clearTimeout(autoTimer);
  if(worker)return;try{controls();}catch(e){status(e.message,true);return;}result=null;$('supplyText').textContent='Inputs changed; calculate to update.';$('wallResults').textContent='Inputs changed; calculate to update.';supplyPlot();$('csv').disabled=true;$('budget').hidden=true;$('chartpanel').hidden=true;
  for(const k of ['R','P','max','avg','rate','seconds'])$('s'+k).textContent='—';
  try{model=previewGrid(params());updateMeshDimensions();status(model.N.toLocaleString()+' solid cells | grid '+model.nx+' × '+model.ny+' × '+model.nz+(model.tubeRefined?' | tube wall/bore automatically resolved':'')+(model.thinFlowRefined?' | thin-plate gas mesh: thickness prioritized; actual X/Y/Z counts shown':'')+' | automatic calculation pending…');draw();scheduleAutoSolve();}catch(e){model=null;status(e.message,true);draw();}
}
for(const k of keys)$(k).addEventListener('input',()=>{if(['rho','k','alpha','density','cp'].includes(k))$('material').value='custom';if(k==='rho'&&Number($('rho').value)>0)$('rhoslider').value=Math.log10(Number($('rho').value));invalidate();});
$('material').onchange=selectMaterial;
$('rhoslider').oninput=()=>{$('rho').value=Number((10**Number($('rhoslider').value)).toPrecision(5));$('material').value='custom';invalidate();};
function setBusy(b){for(const el of document.querySelectorAll('.inputs input,.inputs select,.inputs textarea'))el.disabled=b;$('material').disabled=b;$('solve').disabled=b;$('solveTop').disabled=b;$('cancel').disabled=!b;if(!b)controls();$('progress').hidden=!b;}
function run(){
  clearTimeout(autoTimer);
  if(worker)return;if($('initialMode').value==='saved'&&$('study').value==='transient'&&!savedInitialState){status('Use a completed field or choose Uniform temperature.',true);return;}if(typeof screeningIsRunning==='function'&&screeningIsRunning()){status('Screening is running. Stop it before a Model solve.');return;}let p;try{p=params();model=previewGrid(p);}catch(e){status(e.message,true);return;}
  result=null;for(const k of ['R','P','max','avg','rate','seconds'])$('s'+k).textContent='—';$('csv').disabled=true;$('budget').hidden=true;$('chartpanel').hidden=true;setBusy(true);draw();status('Solving '+model.N.toLocaleString()+' cells…');$('progress').removeAttribute('value');
  const code=$('engine').textContent+'\nonmessage=e=>{try{postMessage({done:solveModel(e.data,p=>postMessage({progress:p}))});}catch(err){postMessage({error:err.message});}};';
  const url=URL.createObjectURL(new Blob([code],{type:'application/javascript'}));
  try{worker=solverWorker||(solverWorker=new Worker(url));}catch(e){URL.revokeObjectURL(url);setBusy(false);status('Cannot start worker: '+e.message,true);return;}URL.revokeObjectURL(url);
  worker.onmessage=e=>{const data=e.data;if(data.progress){const z=data.progress;if(z.message){status(z.message);return;}status((p.study==='transient'?'t = '+fmt(z.time)+' / '+p.duration+' s | ':'')+(z.iteration?'iteration '+z.iteration+' | ΔT '+fmt(z.delta,6)+' K':'time step completed'));if(p.study==='transient'){$('progress').max=p.duration;$('progress').value=z.time;}return;}worker=null;setBusy(false);if(data.error){status(data.error,true);return;}result=data.done;result.params=p;lastCompletedState=structuredClone(result.restart);model=result.mesh;showResults();extraResults();};
  worker.onerror=e=>{worker.terminate();solverWorker=null;worker=null;setBusy(false);status(e.message||'Worker failed.',true);};worker.postMessage(p);
}
$('solve').onclick=run;$('solveTop').onclick=run;$('cancel').onclick=()=>{clearTimeout(autoTimer);if(worker){worker.terminate();solverWorker=null;worker=null;setBusy(false);status('Cancelled. No new converged result.');}};
function showResults(){const s=result.stats;updateMeshDimensions();$('restartInfo').textContent='Completed field available | '+result.restart.temperatureK.length+' cells | '+result.params.study;for(const k of ['R','P','max','avg','rate','seconds'])$('s'+k).textContent=fmt(s[k],k==='R'?5:2);$('csv').disabled=false;
  status(s.limiter+' | '+fmt(s.V)+' V | '+fmt(s.I)+' A | '+model.N.toLocaleString()+' solid cells | grid '+model.nx+' × '+model.ny+' × '+model.nz+(model.thinFlowRefined?' | thickness-prioritized gas mesh':'')+' | heat balance residual '+fmt(s.energyError*100,6)+'%');
  const parts=[[(result.gas?'To channel / gas':'To ambient'),fmt(s.ambient)+' W'],['To electrodes',fmt(s.contacts)+' W'],['Current balance residual',fmt(s.chargeError*100,7)+'%'],['Solid volume',fmt(s.volume*1e6)+' cm³']];
  if(result.params.study==='transient')parts.push(['Integrated input',fmt(s.inputEnergy)+' J'],['Stored heat',fmt(s.stored)+' J'],['Integrated heat loss',fmt(s.lossEnergy)+' J'],['Integrated balance residual',fmt(s.integratedError*100,6)+'%']);
  if(result.gas){const g=result.gas.stats;parts.push(['Pressure drop',fmt(g.dp,7)+' Pa'],['Gas outlet',fmt(g.outlet,2)+' °C'],['Channel Reynolds number',fmt(g.Re,4)+(g.Re>=1?' | inertia omitted: outside quantitative scope':' | Stokes approximation')],['Inlet / outlet flow',fmt(g.Qin*6e7,5)+' / '+fmt(g.Qout*6e7,5)+' mL/min'],['Gas enthalpy gain',fmt(g.enthalpy,5)+' W'],['Gas mass residual',fmt(g.massError*100,6)+'%']);}
  $('budget').replaceChildren(...parts.map(([k,v])=>{const el=document.createElement('div');el.textContent=k+': '+v;return el;}));$('budget').hidden=false;$('chartpanel').hidden=result.params.study!=='transient';status($('status').textContent+' | Grid '+(result.cache.gridReused?'reused':'built')+(result.gas?' | Flow '+(result.cache.flowReused?'reused':'solved'):''));draw();chart();
}
function sizeCanvas(canvas){const box=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.round(box.width*ratio));canvas.height=Math.max(1,Math.round(box.height*ratio));const c=canvas.getContext('2d');c.setTransform(ratio,0,0,ratio,0,0);return[c,box.width,box.height];}
const stops=[[22,13,61],[89,18,105],[168,46,94],[232,91,56],[253,164,45],[246,251,164]];
function colour(v){const t=Math.max(0,Math.min(.999999,v))*(stops.length-1),i=Math.floor(t),f=t-i;return 'rgb('+stops[i].map((n,j)=>Math.round(n+(stops[i+1][j]-n)*f)).join(',')+')';}
function rotation(q){const a=q[0]*Math.cos(yaw)+q[2]*Math.sin(yaw),b=-q[0]*Math.sin(yaw)+q[2]*Math.cos(yaw);return[a,q[1]*Math.cos(pitch)-b*Math.sin(pitch),q[1]*Math.sin(pitch)+b*Math.cos(pitch)];}
function draw(){
  const[c,w,h]=sizeCanvas($('scene'));c.clearRect(0,0,w,h);drawn=[];if(!model)return;
  const gasField=['gasT','speed','pressure'].includes($('field').value)&&result?.gas;const wallField=['wallT','wallGeometry','assembly'].includes($('field').value)&&model.wall3d;const m=$('field').value==='assembly'&&model.assembly?model.assembly:wallField?model.wall3d.mesh:gasField?result.gas.mesh:model;viewModel=m;const scale=.79*Math.min(w,h)/(Math.max(m.L,m.W,m.H))*zoom,proj=q=>{const r=rotation(q);return[w/2+r[0]*scale,h/2-r[1]*scale,r[2]];};
  const field=$('field').value,values=result&&field!=='geometry'&&field!=='wallGeometry'&&field!=='assembly'?(wallField?result.wall?.T:gasField?result.gas[field==='gasT'?'T':field]:result[field]):null;let lo=Infinity,hi=-Infinity;if(values)for(const v of values){lo=Math.min(lo,v);hi=Math.max(hi,v);}
  $('legendtitle').textContent=values?$('field').selectedOptions[0].textContent:'Electrode patches';$('minvalue').textContent=values?fmt(lo):'A | cyan';$('maxvalue').textContent=values?fmt(hi):'B | orange';document.querySelector('.ramp').style.background=values?'':'linear-gradient(90deg,#26b9cf,#f39c43)';
  const axis=$('cut').value==='none'?-1:Number($('cut').value),dims=[m.W,m.H,m.L],threshold=axis<0?0:(Number($('slice').value)/100-.5)*dims[axis];
  const shown=Uint8Array.from(m.xyz,q=>axis<0||q[axis]<=threshold),faces=m.faces.filter(f=>shown[f[0]]);
  if(axis>=0)for(const [a,b,k]of m.edges)if(shown[a]!==shown[b])faces.push(shown[a]?[a,k,1,0]:[b,k,-1,0]);
  for(const [a,k,sign,terminal]of faces){
    let center,points;
    if(m.kind==='annular'){const face=annularFacePolygon(m,a,k,sign);if(rotation(face.normal)[2]<=1e-7)continue;center=face.center;points=face.points.map(proj);}
    else{const normal=[0,0,0];normal[k]=sign;if(rotation(normal)[2]<=1e-7)continue;
    center=m.xyz[a].slice();center[k]+=sign*m.d[k]/2;const axes=[0,1,2].filter(n=>n!==k);points=[];
    for(const[u,v]of [[-1,-1],[1,-1],[1,1],[-1,1]]){const q=center.slice();q[axes[0]]+=u*m.d[axes[0]]/2;q[axes[1]]+=v*m.d[axes[1]]/2;points.push(proj(q));}}
    drawn.push({a,k,sign,terminal,points,depth:proj(center)[2],fill:values?colour(hi===lo?.5:(values[a]-lo)/(hi-lo)):terminal===1?'#26b9cf':terminal===2?'#f39c43':m.region?.[a]===3?'#dedede':m.region?.[a]?'#797979':'#b4b4b4'});
  }
  drawn.sort((a,b)=>a.depth-b.depth);
  for(const face of drawn){c.beginPath();face.points.forEach((q,i)=>i?c.lineTo(q[0],q[1]):c.moveTo(q[0],q[1]));c.closePath();c.fillStyle=face.fill;c.fill();c.strokeStyle=$('mesh').checked?'rgba(20,35,60,.35)':face.fill;c.lineWidth=$('mesh').checked?.55:.5;c.stroke();}
  for(const[list,label]of [[m.termA,'A'],[m.termB,'B']]){if(!list.length)continue;const q=[0,0,m.xyz[list[0]][2]+(label==='A'?-1:1)*m.d[2]/2];for(const a of list){q[0]+=m.xyz[a][0]/list.length;q[1]+=m.xyz[a][1]/list.length;}const r=proj(q);c.fillStyle='#292929';c.beginPath();c.arc(r[0],r[1],11,0,2*Math.PI);c.fill();c.fillStyle='#fff';c.font= '14px Helvetica, Arial, sans-serif' ;c.textAlign='center';c.textBaseline='middle';c.fillText(label,r[0],r[1]);}
  [['X','#a5373c',[1,0,0]],['Y','#247858',[0,1,0]],['Z','#235fbc',[0,0,1]]].forEach(([name,color,q])=>{const r=rotation(q);c.strokeStyle=color;c.beginPath();c.moveTo(48,h-49);c.lineTo(48+r[0]*30,h-49-r[1]*30);c.stroke();c.fillStyle=color;c.font= '13px Helvetica, Arial, sans-serif' ;c.fillText(name,48+r[0]*40,h-49-r[1]*40);});
  $('viewhint').textContent=(result?'Solved field':'Geometry preview')+' | drag to rotate | scroll to zoom'+(axis>=0?' | '+['X','Y','Z'][axis]+' ≤ '+fmt(threshold*1000)+' mm':'');
}
function inside(x,y,points){let hit=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const a=points[i],b=points[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])hit=!hit;}return hit;}
$('scene').onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,total:0};$('scene').setPointerCapture(e.pointerId);};
$('scene').onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.total+=Math.abs(dx)+Math.abs(dy);yaw+=dx*.008;pitch=Math.max(-1.4,Math.min(1.4,pitch+dy*.008));drag.x=e.clientX;drag.y=e.clientY;draw();};
$('scene').onpointerup=e=>{const moved=drag?.total||0;drag=null;if(moved>5||!model)return;const box=$('scene').getBoundingClientRect(),face=[...drawn].reverse().find(f=>inside(e.clientX-box.left,e.clientY-box.top,f.points));if(!face)return;
  const pick=$('pick').value;if(pick!=='none'&&!worker&&viewModel===model){const sign=pick==='A'?-1:1;if(face.k!==2||face.sign!==sign||Math.abs(model.xyz[face.a][2]-model.xyz[(pick==='A'?model.termA:model.termB)[0]][2])>1e-9){$('probe').textContent='Rotate to the '+(sign<0?'−Z':' +Z')+' end face.';return;}$('offset'+pick).value=Math.max(-80,Math.min(80,Math.round(model.xyz[face.a][0]/(Number($('width').value)/2000)*100)));invalidate();return;}
  const q=viewModel.xyz[face.a].map(v=>fmt(v*1000,2)).join(', '),field=$('field').value,arr=field==='wallT'?result?.wall?.T:['gasT','speed','pressure'].includes(field)?result?.gas?.[field==='gasT'?'T':field]:result?.[field];$('probe').textContent='('+q+') mm'+(arr?' | '+fmt(arr[face.a])+' '+{wallT:'°C',T:'°C',phi:'V',q:'W/m³',J:'A/m²',gasT:'°C',speed:'m/s',pressure:'Pa'}[field]:'');};
$('scene').onpointercancel=()=>drag=null;$('scene').addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.45,Math.min(3,zoom*Math.exp(-e.deltaY*.001)));draw();},{passive:false});
for(const k of ['field','mesh','slice','cut'])$(k).oninput=()=>{$('slice').hidden=$('cut').value==='none';draw();};$('fit').onclick=()=>{yaw=.78;pitch=.38;zoom=1.3;draw();};
function chart(){mountFigure('history',result&&result.params.study==='transient'?Figure5.history(result):null);}
function download(name,text,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('json').onclick=()=>download('joule3d-settings.json',JSON.stringify({schema:'joule3d-draft-1',parameters:result?result.params:params(),stats:result?.stats},null,2),'application/json');
$('csv').onclick=()=>{if(!result)return;const lines=['phase,x_m,y_m,z_m,T_C,potential_V,qJ_W_m3,J_A_m2,speed_m_s,pressure_Pa,ux_m_s,uy_m_s,uz_m_s'];result.mesh.xyz.forEach((q,i)=>lines.push([result.mesh.region[i]?'electrode_'+result.mesh.region[i]:'heater',...q,result.T[i],result.phi[i],result.q[i],result.J[i],'','','','',''].join(',')));if(result.gas){const g=result.gas;g.mesh.xyz.forEach((q,i)=>lines.push(['gas',...q,g.T[i],'','','',g.speed[i],g.pressure[i],...g.U[i]].join(',')));}if(result.wall?.mesh)result.wall.mesh.xyz.forEach((q,i)=>lines.push(['wall',...q,result.wall.T[i],'','','','','','','',''].join(',')));download('joule3d-field.csv',lines.join('\n'),'text/csv');};
for(const k of ['work','screening','method'])$(k+'tab').onclick=()=>{$('workspace').hidden=k!=='work';$('screening').hidden=k!=='screening';$('method').hidden=k!=='method';for(const tab of ['work','screening','method'])$(tab+'tab').setAttribute('aria-pressed',tab===k);if(k==='work'){draw();chart();if(!result)scheduleAutoSolve();}if(k==='screening')screeningRender();};

$('flow').onchange=()=>{if(!$('flow').checked&&['gasT','speed','pressure'].includes($('field').value))$('field').value='T';invalidate();};
function fitCAD(){const union=cadParts.filter(a=>a.op==='union');if(!union.length)return;const dims=[0,0,0];for(const a of union){const size=[a.type==='cylinder'?a.diameter:a.width,a.type==='cylinder'?a.diameter:a.height,a.length];[a.x,a.y,a.z].forEach((v,i)=>dims[i]=Math.max(dims[i],2*Math.abs(v)+size[i]));}['width','height','length'].forEach((k,i)=>$(k).value=dims[i]);$('channelWidth').value=Math.max(Number($('channelWidth').value),dims[0]*1.5);$('channelHeight').value=Math.max(Number($('channelHeight').value),dims[1]*1.5);}
function partsDisplay(){const list=$('cadTarget').value==='wall'?wallParts:cadParts;const out=$('partlist');out.replaceChildren(...list.map((a,i)=>{const row=document.createElement('div'),b=document.createElement('button');row.textContent=(i+1)+'. '+a.op+' '+a.type+' ('+a.x+', '+a.y+', '+a.z+') mm ';b.textContent='Remove';b.onclick=()=>{list.splice(i,1);if(list===wallParts)fitWallCAD();else fitCAD();partsDisplay();invalidate();};row.append(b);return row;}));}
$('addpart').onclick=()=>{if(worker)return;const a={type:$('parttype').value,op:$('partop').value,width:Number($('partwidth').value),height:Number($('partheight').value),diameter:Number($('partwidth').value),length:Number($('partlength').value),x:Number($('partx').value),y:Number($('party').value),z:Number($('partz').value)};if(![a.width,a.height,a.length].every(v=>v>0)){status('CAD dimensions must be positive.',true);return;}if($('cadTarget').value==='wall'){wallParts.push(a);fitWallCAD();$('wall').checked=true;$('flow').checked=true;$('wallGeometry').value='cad3d';$('field').value='assembly';}else{cadParts.push(a);fitCAD();$('shape').value='cad';}partsDisplay();invalidate();};
$('clearparts').onclick=()=>{if(worker)return;if($('cadTarget').value==='wall')wallParts=[];else cadParts=[];partsDisplay();invalidate();};
$('stlfile').onchange=async e=>{if(worker)return;try{const file=e.target.files[0];if(!file)return;const parsed=parseSTL(await file.arrayBuffer());stlTriangles=parsed.triangles;['width','height','length'].forEach((k,i)=>$(k).value=Number(parsed.dimensions[i].toPrecision(6)));$('channelWidth').value=Math.max(Number($('channelWidth').value),parsed.dimensions[0]*1.5);$('channelHeight').value=Math.max(Number($('channelHeight').value),parsed.dimensions[1]*1.5);$('shape').value='stl';$('stlinfo').textContent=file.name+' | '+stlTriangles.length+' triangles | closed edges checked';invalidate();}catch(err){status(err.message,true);}};
$('stlexport').onclick=()=>{if(!model)return;if(model.kind==='annular'){const lines=['solid Joule3D'];for(const[a,k,sign]of model.faces){const f=annularFacePolygon(model,a,k,sign),v=f.points.map(p=>p.map(x=>x*1000)),u=v[1].map((x,i)=>x-v[0][i]),w=v[2].map((x,i)=>x-v[0][i]),cross=[u[1]*w[2]-u[2]*w[1],u[2]*w[0]-u[0]*w[2],u[0]*w[1]-u[1]*w[0]];if(cross.reduce((s,x,i)=>s+x*f.normal[i],0)<0)v.reverse();for(const tri of [[0,1,2],[0,2,3]])lines.push('facet normal '+f.normal.join(' '),'outer loop',...tri.map(i=>'vertex '+v[i].join(' ')),'endloop','endfacet');}lines.push('endsolid Joule3D');download('joule3d-annular.stl',lines.join('\n'),'model/stl');return;}const lines=['solid Joule3D'];for(const[a,k,sign]of model.faces){const center=model.xyz[a].map(v=>v*1000);center[k]+=sign*model.d[k]*500;const axes=[0,1,2].filter(v=>v!==k),vertices=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([u,v])=>{const q=center.slice();q[axes[0]]+=u*model.d[axes[0]]*500;q[axes[1]]+=v*model.d[axes[1]]*500;return q;});if((k===1?-1:1)!==sign)vertices.reverse();const normal=[0,0,0];normal[k]=sign;for(const inds of [[0,1,2],[0,2,3]])lines.push('facet normal '+normal.join(' '),'outer loop',...inds.map(i=>'vertex '+vertices[i].join(' ')),'endloop','endfacet');}lines.push('endsolid Joule3D');download('joule3d-voxel.stl',lines.join('\n'),'model/stl');};

new ResizeObserver(()=>{draw();chart();}).observe($('scene'));window.addEventListener('resize',chart);controls();invalidate();

function updateMeshDimensions(){if(!model)return;const m=model,p=params();if(m.kind==='annular'){$('meshDimensions').textContent='Annular grid '+m.nr+' × '+m.nt+' × '+m.nz+' | OD '+p.width+' mm | Bore '+p.bore+' mm | Radial spacing '+fmt(m.dr*1000,4)+' mm';return;}const ext=[0,1,2].map(a=>{const c=m.xyz.map(q=>q[a]);return (Math.max(...c)-Math.min(...c)+m.d[a])*1000;});$('meshDimensions').textContent='Grid '+m.nx+' × '+m.ny+' × '+m.nz+' | Represented solid X / Y / Z: '+ext.map(v=>fmt(v,4)).join(' / ')+' mm | Cell spacing: '+m.d.map(v=>fmt(v*1000,4)).join(' / ')+' mm';}
$('useCompletedField').onclick=()=>{if(worker)return;if(!lastCompletedState){status('Complete a calculation first.',true);return;}savedInitialState=structuredClone(lastCompletedState);$('initialMode').value='saved';$('study').value='transient';$('restartInfo').textContent='Saved field selected | '+savedInitialState.temperatureK.length+' cells';invalidate();};

$('plateMesh').onclick=()=>{if(worker)return;if($('shape').value!=='block'||$('flow').checked||$('wall').checked){status('Thin plate grid applies to a rectangular solid with gas and wall disabled. Independent X / Y / Z counts remain available for other cases.',true);return;}$('meshType').value='cartesian';$('nx').value=16;$('ny').value=6;$('nz').value=60;invalidate();};
