/* Study persistence and comparison. Never render imported strings as HTML. */
function parseRhoTable(){const text=$('rhoTable').value.trim();if(!text)return [];return text.split(/\n+/).map(line=>line.trim().split(/[\s,;]+/).map(Number));}
function thermalTableBindings(){return [['kTable','kCurve'],['cpTable','cpCurve'],['electrodeKTable','electrodeKCurve'],['electrodeCpTable','electrodeCpCurve'],['electrodeRhoTable','electrodeRhoCurve']];}
function parseThermalTables(){return Object.fromEntries(thermalTableBindings().map(([id,key])=>[key,$(id).value.trim()?$(id).value.trim().split(/\n+/).map(line=>line.trim().split(/[\s,;]+/).map(Number)):[]]));}
for(const [id]of thermalTableBindings())$(id).oninput=invalidate;
$('wall').onchange=()=>{if($('wall').checked&&wall3DEnabled(params()))$('field').value='assembly';invalidate();};
$('rhoTable').oninput=invalidate;
$('materialSource').oninput=invalidate;
$('wallMaterial').onchange=()=>{const rows={quartz:[1.4,730,2200],alumina:[25,880,3950],steel:[16,500,8000]},v=rows[$('wallMaterial').value];if(v){['wallK','wallCp','wallDensity'].forEach((k,i)=>$(k).value=v[i]);invalidate();}};
for(const k of ['wallK','wallCp','wallDensity'])$(k).addEventListener('input',()=>$('wallMaterial').value='custom');
let cases=[];try{const saved=JSON.parse(localStorage.getItem('joule3d.cases.v3')||'[]');if(Array.isArray(saved))cases=saved.filter(c=>c&&c.parameters&&c.stats).slice(-12);}catch{}
function loadParameters(p){
 p=structuredClone(p);
 p={meshType:'cartesian',nr:4,nt:48,initialMode:'uniform',...p};
 if(!p||typeof p!=='object')throw Error('Missing parameters object.');
 for(const k of keys){if(p[k]===undefined)continue;if(strings.has(k)){if(!Array.from($(k).options).some(o=>o.value===p[k]))throw Error('Unsupported '+k);}else if(!Number.isFinite(p[k]))throw Error('Invalid '+k);}
 if(p.parts&&!Array.isArray(p.parts))throw Error('Invalid CAD parts.');
 if(p.triangles&&(!Array.isArray(p.triangles)||p.triangles.length>20000||p.triangles.some(t=>!Array.isArray(t)||t.length!==3||t.some(v=>!Array.isArray(v)||v.length!==3||!v.every(Number.isFinite)))))throw Error('Invalid STL triangle data.');
 for(const [id,key]of [['rhoTable','rhoCurve'],...thermalTableBindings()])materialTable(p[key],1,key);
 if(p.initialMode==='saved'&&(!p.initialState||!Array.isArray(p.initialState.temperatureK)||p.initialState.temperatureK.length>180000||!p.initialState.temperatureK.every(t=>Number.isFinite(t)&&t>0)))throw Error('Missing or invalid saved temperature field.');
 // Validate a complete candidate before modifying visible controls.
 const candidate={...params(),wallGeometry:'axial',wallParts:[],wallTriangles:null,...p};makeGrid(candidate);
 if(p.n!==undefined&&!Array.from($('n').options).some(o=>Number(o.value)===p.n)){const o=document.createElement('option');o.value=String(p.n);o.textContent='Imported grid | '+p.n;$('n').append(o);}
 savedInitialState=p.initialState||null;
 for(const k of keys)if(p[k]!==undefined)$(k).value=p[k];
 for(const [id,key]of thermalTableBindings())$(id).value=(p[key]||[]).map(r=>r.join(', ')).join('\n');
 $('flow').checked=!!p.flow;$('wall').checked=!!p.wall;$('rhoTable').value=(p.rhoCurve||[]).map(r=>r.join(', ')).join('\n');$('materialSource').value=p.materialSource||'';
 cadParts=p.parts||[];stlTriangles=p.triangles||null;wallParts=p.wallParts||[];wallTriangles=p.wallTriangles||null;$('wallGeometry').value=p.wallGeometry||'axial';$('material').value='custom';describeMaterial();partsDisplay();invalidate();status('Design loaded. Automatic calculation starts in Model.');
}
$('importCase').onchange=async e=>{if(worker)return;try{const file=e.target.files[0];if(!file)return;if(file.size>12e6)throw Error('JSON exceeds 12 MB.');const data=JSON.parse(await file.text());loadParameters(data.parameters);restoreBenchmarkMetadata(data.benchmark);}catch(err){status(err.message,true);}finally{e.target.value='';}};
function caseTable(){const host=$('caseList');host.replaceChildren();if(!cases.length){host.textContent='Save a completed calculation to compare designs on this device.';return;}const table=document.createElement('table'),head=table.createTHead().insertRow();['Case','P (W)','Tmax (°C)','Tavg (°C)','Δp (Pa)','In window',''].forEach(v=>{const th=document.createElement('th');th.textContent=v;head.append(th);});const body=table.createTBody();cases.forEach((c,i)=>{const row=body.insertRow();[c.name,fmt(c.stats.P),fmt(c.stats.max,1),fmt(c.stats.avg,1),fmt(c.dp,6),fmt(c.stats.targetFraction*100,1)+'%'].forEach(v=>row.insertCell().textContent=v);const cell=row.insertCell();for(const [label,fn]of [['Load',()=>{try{loadParameters(c.parameters);restoreBenchmarkMetadata(c.benchmark);}catch(e){status(e.message,true);}}],['Remove',()=>{cases.splice(i,1);persistCases();caseTable();}]]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{if(!worker)fn();};cell.append(b);}});host.append(table);}
function persistCases(){try{localStorage.setItem('joule3d.cases.v3',JSON.stringify(cases));return true;}catch{status('Device storage is unavailable or full. Export settings JSON to preserve this design.',true);return false;}}
$('saveCase').onclick=()=>{if(!result||worker){status('Complete a calculation before saving a design.',true);return;}cases.push({name:new Date().toLocaleString(),parameters:structuredClone(result.params),benchmark:benchmarkMetadata(),stats:structuredClone(result.stats),dp:result.gas?.stats.dp});if(cases.length>12)cases.shift();const saved=persistCases();caseTable();if(saved)status('Design saved on this device. Comparison uses each case’s own boundary conditions.');};
function supplyPlot(){mountFigure('supplyPlot',result?Figure5.supply(result):null);}
function extraResults(){const s=result.stats;$('supplyText').textContent='Requested '+result.params.command+' '+result.params.mode+' | actual '+fmt(s.V)+' V / '+fmt(s.I)+' A / '+fmt(s.P)+' W | '+s.limiter+' | contact heat '+fmt(s.contactPower)+' W | peak J '+fmt(s.peakJ)+' A/m² | target-window volume '+fmt(s.targetFraction*100,1)+'% | heater maximum '+fmt(s.heaterMax,2)+' °C | electrode maximum '+fmt(s.electrodeMax,2)+' °C';
 const host=$('wallResults');host.replaceChildren();if(result.wall?.mesh){const w=result.wall.stats;host.textContent='3D wall | '+w.cells+' cells | '+fmt(w.volume*1e6,3)+' cm³ | '+fmt(w.min,2)+'–'+fmt(w.max,2)+' °C | normal-ray coverage '+fmt(w.rayFraction*100,1)+'%. Select Wall temperature and Cut to inspect.';}else if(result.wall){const table=document.createElement('table'),head=table.createTHead().insertRow();['z (mm)','Inner cell (°C)','Outer cell (°C)'].forEach(v=>{const th=document.createElement('th');th.textContent=v;head.append(th);});const body=table.createTBody();result.wall.inner.forEach((t,i)=>{const row=body.insertRow();[fmt(((i+.5)*model.d[2]-model.L/2)*1000,2),fmt(t,2),fmt(result.wall.outer[i],2)].forEach(v=>row.insertCell().textContent=v);});const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Wall maximum '+fmt(Math.max(...result.wall.inner,...result.wall.outer),2)+' °C | show axial temperatures';details.append(summary,table);host.append(details);}else host.textContent='Wall not included in this calculation.';supplyPlot();}
window.addEventListener('resize',supplyPlot);caseTable();

function fitWallCAD(){const union=wallParts.filter(a=>a.op==='union');if(!union.length)return;const dims=[0,0,0];for(const a of union){const sizes=[a.type==='cylinder'?a.diameter:a.width,a.type==='cylinder'?a.diameter:a.height,a.length];[a.x||0,a.y||0,a.z||0].forEach((v,i)=>dims[i]=Math.max(dims[i],2*Math.abs(v)+sizes[i]));}['wallWidth','wallHeight','length'].forEach((id,i)=>$(id).value=dims[i]);}
$('cadTarget').onchange=partsDisplay;
$('wallStlFile').onchange=async e=>{if(worker)return;try{const file=e.target.files[0];if(!file)return;if(file.size>12e6)throw Error('Wall STL exceeds 12 MB.');const parsed=parseSTL(await file.arrayBuffer());wallTriangles=parsed.triangles;['wallWidth','wallHeight','length'].forEach((id,i)=>$(id).value=Number(parsed.dimensions[i].toPrecision(7)));$('wallGeometry').value='stl3d';$('field').value='assembly';$('wall').checked=true;$('flow').checked=true;$('wallStlInfo').textContent=file.name+' | '+wallTriangles.length+' triangles | centered; total length '+fmt(parsed.dimensions[2])+' mm';invalidate();}catch(err){status(err.message,true);}};
