/* Scientific figures. Coordinates are points: 72 pt = 1 inch.
   A 360 × 360 pt panel includes axes/labels. Colorbars and legends are extra. */
const Figure5 = (()=>{
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
 const number=v=>v===0?'0':Math.abs(v)>=1e4||Math.abs(v)<.001?Number(v.toPrecision(3)).toExponential().replace('e+','e'):String(Number(v.toPrecision(4)));
 const viridis=t=>{const stops=[[68,1,84],[72,36,117],[65,68,135],[53,95,141],[42,120,142],[33,145,140],[34,168,132],[68,191,112],[122,209,81],[189,223,38],[253,231,37]],u=(.85-.75*Math.max(0,Math.min(1,t)))*10,i=Math.floor(u),f=u-i;return 'rgb('+stops[i].map((a,k)=>Math.round(a*(1-f)+stops[Math.min(10,i+1)][k]*f)).join(',')+')';};
 function axis(lo,hi,log=false){if(!Number.isFinite(lo+hi)||hi<=lo||log&&lo<=0)throw Error('Invalid figure axis range.');let ticks=[],minor=[];
  if(log){const a=Math.floor(Math.log10(lo)),b=Math.ceil(Math.log10(hi));lo=10**a;hi=10**b;const stride=Math.max(1,Math.ceil((b-a)/4));for(let e=a;e<=b;e++){if((e-a)%stride===0||e===b)ticks.push({v:10**e,label:'10',exp:e});for(let n=2;n<10;n++)if(n*10**e<hi)minor.push(n*10**e);}}
  else {const raw=(hi-lo)/4,p=10**Math.floor(Math.log10(raw)),step=[1,2,2.5,5,10].find(v=>v*p>=raw)*p;for(let v=Math.ceil(lo/step)*step;v<=hi+step*1e-8;v+=step)ticks.push({v:Math.abs(v)<step*1e-8?0:v,label:number(Math.abs(v)<step*1e-8?0:v)});for(let v=Math.ceil(lo/(step/2))*step/2;v<hi;v+=step/2)if(!ticks.some(t=>Math.abs(t.v-v)<step*1e-7))minor.push(v);}
  const f=log?Math.log10:v=>v;return {lo,hi,ticks,minor,map:v=>(f(v)-f(lo))/(f(hi)-f(lo))};
 }
 function figure(xa,ya,xlabel,ylabel,{bar=false,legend=false}={}){
  const f={width:bar?504:360,height:legend?400:360,L:78,R:338,T:20,B:280,parts:[],xa,ya};f.x=v=>f.L+260*xa.map(v);f.y=v=>f.B-260*ya.map(v);
  f.line=(x1,y1,x2,y2,color='#222',width=1.2,dash='')=>f.parts.push(`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="${width}"${dash?` stroke-dasharray="${dash}"`:''}/>`);
  f.rect=(x,y,w,h,color)=>f.parts.push(`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${color}" shape-rendering="crispEdges"/>`);
  f.text=(x,y,text,size=15,anchor='middle',rotate=0,exp=null)=>{let lines=[String(text)];if(size===18){const limit=rotate?260:320;let line='';lines=[];for(const word of String(text).split(' ')){const test=line?line+' '+word:word;if(test.length*size*.54>limit&&line){lines.push(line);line=word;}else line=test;}lines.push(line);}const content=lines.map((line,i)=>`<tspan x="${x}" dy="${i?20:0}">${escape(line).replace(/[²³]/g,c=>`<tspan baseline-shift="super" font-size="${size*.7}">${c==='²'?2:3}</tspan>`)}</tspan>`).join('');f.parts.push(`<text id="label-${f.parts.length}" x="${x}" y="${y}" font-size="${size}" text-anchor="${anchor}"${rotate?` transform="rotate(${rotate} ${x} ${y})"`:''}>${content}${exp===null?'':`<tspan baseline-shift="super" font-size="${size*.7}">${exp}</tspan>`}</text>`);};

  f.path=(points,color,width=2.5,dash='')=>f.parts.push(`<polyline points="${points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${color}" stroke-width="${width}"${dash?` stroke-dasharray="${dash}"`:''}/>`);
  f.dot=(x,y,color,r=5)=>f.parts.push(`<circle cx="${x}" cy="${y}" r="${r}" fill="${color}"/>`);
  f.frame=()=>{f.parts=[`<defs><clipPath id="plot-clip"><rect x="${f.L}" y="${f.T}" width="${f.R-f.L}" height="${f.B-f.T}"/></clipPath></defs><g clip-path="url(#plot-clip)">`,...f.parts,'</g>'];f.parts.push(`<rect id="primary-axes" x="${f.L}" y="${f.T}" width="${f.R-f.L}" height="${f.B-f.T}" fill="none" stroke="#222" stroke-width="1.2"/>`);for(const [a,horizontal]of [[xa,true],[ya,false]])for(const major of [false,true])for(const tick of major?a.ticks:a.minor.map(v=>({v}))){const pos=horizontal?f.x(tick.v):f.y(tick.v),len=major?6:3,width=major?1.2:.9;if(horizontal){f.line(pos,f.B,pos,f.B-len,'#222',width);f.line(pos,f.T,pos,f.T+len,'#222',width);if(major)f.text(pos,f.B+23,tick.label,15,'middle',0,tick.exp??null);}else{f.line(f.L,pos,f.L+len,pos,'#222',width);f.line(f.R,pos,f.R-len,pos,'#222',width);if(major)f.text(f.L-9,pos+5,tick.label,15,'end',0,tick.exp??null);}}f.text((f.L+f.R)/2,337,xlabel,18);f.text(22,(f.T+f.B)/2,ylabel,18,'middle',-90);};
  f.legend=(items)=>{const spacing=320/items.length;items.forEach(([label,col,dash],i)=>{const xx=23+i*spacing;f.line(xx,380,xx+22,380,col,dash?1.8:2.5,dash||'');f.text(xx+29,385,label,14,'start');});};
  f.svg=()=>`<svg xmlns="http://www.w3.org/2000/svg" width="${f.width/72}in" height="${f.height/72}in" viewBox="0 0 ${f.width} ${f.height}" font-family="Arial, Helvetica, DejaVu Sans, sans-serif" fill="#222"><rect width="100%" height="100%" fill="white"/>${f.parts.join('')}</svg>`;
  return f;
 }
 function history(r){const rows=r.history,low=Math.min(...rows.map(v=>v.avg)),high=Math.max(...rows.map(v=>v.max)),pad=Math.max(1,(high-low)*.08),f=figure(axis(0,r.params.duration),axis(low-pad,high+pad),'Time (s)','Temperature (°C)',{legend:true});for(const [k,col]of [['avg',viridis(0)],['max',viridis(1)]])f.path(rows.map(v=>[f.x(v.t),f.y(v[k])]),col);f.frame();f.legend([['Average',viridis(0)],['Maximum',viridis(1)]]);return f;}
 function supply(r){const p=r.params,f=figure(axis(0,p.vmax),axis(0,p.imax),'Voltage (V)','Current (A)',{legend:true});f.path(Array.from({length:401},(_,i)=>{const v=p.vmax*i/400;return [f.x(v),f.y(Math.min(p.imax,v?p.pmax/v:p.imax))];}),'#000',1.8,'6 4');f.path(r.history.filter(v=>Number.isFinite(v.V)&&Number.isFinite(v.I)).map(v=>[f.x(v.V),f.y(v.I)]),viridis(.5));f.dot(f.x(r.stats.V),f.y(r.stats.I),viridis(1));f.frame();f.legend([['Supply limit','#000','6 4'],['Trajectory',viridis(.5)]]);return f;}
 function checkDimensions(f){const ratio=(f.R-f.L)/(f.B-f.T);if(Math.abs(ratio-1)>.01||f.width<360||f.height<360)throw Error('Figure dimensions failed: export blocked.');return {panelIn:[5,5],axesIn:[(f.R-f.L)/72,(f.B-f.T)/72],ratio,exportIn:[f.width/72,f.height/72],pngPixels:[Math.round(f.width/72*600),Math.round(f.height/72*600)]};}
 return {figure,axis,viridis,number,history,supply,checkDimensions};
})();
if(typeof module!=='undefined')module.exports=Figure5;
