// Short per-material note; caveats shared by every preset are stated once above the table.
function materialDescription(m){const v=materialPresetValues(m),tables=[['ρe',v.rhoCurve],['k',v.kCurve],['Cp',v.cpCurve]].filter(([,t])=>t.length);const range=tables.length?tables.map(([k,t])=>k).join(', ')+' tabulated '+Math.max(...tables.map(([,t])=>t[0][0]))+'–'+Math.min(...tables.map(([,t])=>t.at(-1)[0]))+' °C':'';return [m.source,m.status&&!/^Transcribed catalog values/.test(m.status)?m.status:'',range,m.rhoAlpha?'linear ρ(T), α20 = '+m.rhoAlpha+' /K':'',m.jmaxBasis?'Jmax: '+m.jmaxBasis:''].filter(Boolean).join('. ')+'.';}
const sig=x=>typeof x==='number'&&Number.isFinite(x)?(Math.abs(x)>=1e-3&&Math.abs(x)<1e5?String(Number(x.toPrecision(4))):x.toExponential(3).replace(/\.?0+e/,'e')):x;
function describeMaterial(){const m=materialCatalog.find(v=>v.id===$('material').value);$('materialInfo').textContent=m?materialDescription(m):'Custom properties. The source text below is kept as an editable record.';}
function selectMaterial(){const m=materialCatalog.find(v=>v.id===$('material').value);if(m){const v=materialPresetValues(m);for(const key of ['rho','alpha','k','cp','density'])$(key).value=v[key];for(const [id,key]of [['rhoTable','rhoCurve'],['kTable','kCurve'],['cpTable','cpCurve']])$(id).value=v[key].map(r=>r.join(', ')).join('\n');$('rhoslider').value=Math.log10(v.rho);$('materialSource').value=m.name+'. '+materialDescription(m)+(m.url?' '+m.url:'');}describeMaterial();invalidate();}
function initMaterialCatalog(){const select=$('material'),old=select.value;select.replaceChildren();for(const [label,rows]of [['Materials',materialCatalog.filter(m=>m.id.startsWith('catalog-'))],['Legacy examples',materialCatalog.filter(m=>!m.id.startsWith('catalog-'))]]){const group=document.createElement('optgroup');group.label=label;for(const m of rows){const o=document.createElement('option');o.value=m.id;o.textContent=m.name;group.append(o);}select.append(group);}const o=document.createElement('option');o.value='custom';o.textContent='Custom';select.append(o);select.value=old;select.onchange=selectMaterial;describeMaterial();for(const id of ['rho','alpha','k','cp','density','rhoTable','kTable','cpTable','materialSource','rhoslider'])$(id).addEventListener('input',()=>{select.value='custom';describeMaterial();});const body=$('materialCatalogBody');for(const m of materialCatalog.filter(v=>v.id.startsWith('catalog-'))){const row=document.createElement('tr');const v=materialPresetValues(m);for(const value of [m.name,m.referenceC,sig(m.rhoOhmCm),sig(m.rhoOhmCm*.01),m.density,m.cp,m.k,m.jmax?sig(m.jmax):'–',m.model,materialDescription(m)]){const td=document.createElement('td');td.textContent=value;row.append(td);}if(m.url){const a=document.createElement('a');a.href=m.url;a.textContent=' Source';a.target='_blank';a.rel='noopener';row.lastElementChild.append(a);}body.append(row);}}
// Keep historical constants in the engine for saved cases and benchmarks only.
// The interactive catalog exposes the shared material presets.
initMaterialCatalog();
document.querySelector('#material optgroup[label="Legacy examples"]').remove();
$('material').value='catalog-1';
selectMaterial();
