const sweepFields=[['command','Supply setpoint | selected V/A/W'],['length','Total length | mm'],['width','Heater width / outer diameter | mm'],['height','Heater thickness | mm'],['bore','Tube inner diameter | mm'],['rho','Heater resistivity | Ω m'],['k','Heater k | W/m K'],['cp','Heater Cp | J/kg K'],['alpha','Heater resistivity coefficient | 1/K'],['density','Heater density | kg/m³'],['flowRate','Gas flow | selected Model units'],['gasInlet','Gas inlet | °C'],['channelWidth','Channel width / tube ID | mm'],['channelHeight','Channel height | mm'],['wallThickness','Reactor wall thickness | mm'],['wallK','Wall k | W/m K'],['wallCp','Wall Cp | J/kg K'],['wallDensity','Wall density | kg/m³'],['wallEmissivity','Wall emissivity'],['wallWidth','CAD/STL wall width | mm'],['wallHeight','CAD/STL wall height | mm'],['insulationThickness','Insulation thickness | mm'],['insulationK','Insulation k | W/m K'],['ambient','Ambient temperature | °C'],['h','External h | W/m² K'],['emissivity','Heater emissivity'],['hc','Terminal thermal conductance | W/m² K'],['sink','Terminal sink | °C'],['contact','Terminal patch width | %'],['offsetA','A offset | % half-width'],['offsetB','B offset | % half-width'],['contactR','Electrical contact resistivity | Ω m²'],['thermalR','Thermal contact resistance | m² K/W'],['electrodeLength','Each electrode length | mm'],['electrodeRho','Electrode resistivity | Ω m'],['electrodeK','Electrode k | W/m K'],['electrodeCp','Electrode Cp | J/kg K'],['electrodeDensity','Electrode density | kg/m³'],['vmax','Voltage cap | V'],['imax','Current cap | A'],['pmax','Power cap | W'],['slew','Voltage slew | V/s'],['period','Pulse period | s'],['duty','Pulse duty'],['duration','Duration | s'],['initial','Initial solid temperature | °C'],['mu','Gas viscosity | Pa s'],['gasDensity','Gas density | kg/m³'],['gasCp','Gas Cp | J/kg K'],['gasK','Gas k | W/m K'],['outletPressure','Outlet absolute pressure | Pa']];
const sweepOutputs=[['min','Minimum solid temperature | °C'],['spread','Solid temperature spread | K'],['heaterMax','Heater maximum | °C'],['avg','Heater + electrode average | °C'],['max','Heater + electrode maximum | °C'],['outlet','Gas outlet | °C'],['wallMax','Wall maximum | °C'],['electrodeMax','Electrode maximum | °C'],['P','Actual power | W'],['V','Actual voltage | V'],['I','Actual current | A'],['R','Resistance | Ω'],['dp','Gas pressure drop | Pa'],['Re','Reynolds number'],['contactPower','Contact heat | W'],['peakJ','Peak reconstructed J | A/m²'],['targetPercent','Heater in target window | %'],['rate','Final heating rate | °C/s'],['seconds','Solver time | s'],['energyPercent','Final energy residual | %'],['massPercent','Gas mass residual | %'],['inputEnergy','Transient input | J'],['stored','Stored heat | J'],['integratedPercent','Integrated energy residual | %']];
let sweepState=null,sweepWorker=null,sweepSelected=-1,sweepPlotBounds=null;
function screeningIsRunning(){return !!sweepWorker;}
function screeningStatus(text,error=false){$('sweepStatus').textContent=text;$('sweepStatus').classList.toggle('error',error);}
function screeningActiveReason(key,p){
 const curve={rho:'rhoCurve',alpha:'rhoCurve',k:'kCurve',cp:'cpCurve',electrodeRho:'electrodeRhoCurve',electrodeK:'electrodeKCurve',electrodeCp:'electrodeCpCurve'}[key];if(curve&&p[curve]?.length)return 'A temperature table overrides this scalar. Clear that table in Model first.';
 if(['cp','density','electrodeCp','electrodeDensity','wallCp','wallDensity'].includes(key)&&p.study!=='transient')return 'Solid heat capacity/density affect storage only; select a transient study.';
 if(key==='insulationK'&&!p.insulationThickness)return 'Set nonzero insulation thickness or sweep it on the other axis.';
 if(key==='height'&&!['block','neck','cad','stl'].includes(p.shape))return 'This shape uses diameter, not thickness.';
 if(key==='bore'&&p.shape!=='tube')return 'Select Hollow tube in Model.';
 if(['flowRate','gasInlet','channelWidth','channelHeight','mu','gasDensity','gasCp','gasK','outletPressure'].includes(key)&&!p.flow)return 'Enable gas flow in Model.';
 if(key==='channelHeight'&&p.wall&&p.wallGeometry==='cylinder3d')return 'Cylindrical walls use channel width as inner diameter.';
 if(['channelWidth','channelHeight'].includes(key)&&p.wall&&['cad3d','stl3d'].includes(p.wallGeometry))return 'CAD/STL walls use their outer bounds and explicit bore geometry.';
 if(key.startsWith('wall')&&!p.wall)return 'Enable reactor wall in Model.';
 if(['wallWidth','wallHeight'].includes(key)&&!['cad3d','stl3d'].includes(p.wallGeometry))return 'Outer bounds apply to CAD/STL walls.';
 if(key==='wallThickness'&&['cad3d','stl3d'].includes(p.wallGeometry))return 'CAD/STL walls use explicit geometry; this scalar does not reshape them.';
 if(['insulationThickness','insulationK'].includes(key)&&!p.wall)return 'Enable reactor wall in Model.';
 if(['h','emissivity'].includes(key)&&p.flow&&!p.wall)return 'This boundary term is disabled with gas flow and no wall.';
 if(['electrodeRho','electrodeK','electrodeCp','electrodeDensity'].includes(key)&&!p.electrodeLength)return 'Enable finite electrodes in Model.';
 if(['period','duty','duration','initial','slew'].includes(key)&&p.study!=='transient')return 'Select a transient study in Model.';
 if(key==='outletPressure'&&p.flowUnit!=='standard')return 'Absolute pressure affects standard-flow conversion only.';
 return '';
}
function screeningBusy(b){for(const el of document.querySelectorAll('#sweepSetup input,#sweepSetup select'))el.disabled=b;$('sweepStart').disabled=b;$('sweepStop').disabled=!b;$('sweepResume').disabled=b||!sweepState||!sweepState.rows.some(r=>r===null);$('sweepRestore').disabled=b;$('sweepImport').disabled=b;$('sweepLoad').disabled=b||sweepSelected<0;$('solve').disabled=b||!!worker;$('solveTop').disabled=b||!!worker;}
function screeningPersist(){if(!sweepState)return;try{localStorage.setItem('joule3d.screening.v1',JSON.stringify(sweepState));$('sweepStorage').textContent='Checkpoint saved on this device after every point.';}catch{$('sweepStorage').textContent='Device storage full/unavailable. Export sweep JSON to retain this run.';}}
function screeningAxis(prefix){return {key:$(prefix+'Param').value,min:Number($(prefix+'Min').value),max:Number($(prefix+'Max').value),count:Number($(prefix+'Count').value),scale:$(prefix+'Scale').value};}
function screeningStart(){if(worker){screeningStatus('Wait for the Model calculation or cancel it first.',true);return;}try{const base=structuredClone(params()),x=screeningAxis('sweepX'),y=screeningAxis('sweepY');if(x.key===y.key)throw Error('Choose two different parameters.');const probe={...base,[x.key]:x.max,[y.key]:y.max};for(const a of [x,y]){const reason=screeningActiveReason(a.key,probe);if(reason)throw Error(a.key+': '+reason);}const xs=sweepValues(x.min,x.max,x.count,x.scale),ys=sweepValues(y.min,y.max,y.count,y.scale);if(xs.length*ys.length>400)throw Error('Maximum 400 combinations per run.');sweepState={schema:'joule3d-screening-1',created:new Date().toISOString(),base,x,y,xs,ys,rows:Array(xs.length*ys.length).fill(null)};sweepSelected=-1;screeningPersist();screeningLaunch();}catch(e){screeningStatus(e.message,true);}}
function screeningLaunch(){if(worker){screeningStatus('Wait for the Model calculation or cancel it first.',true);return;}if(sweepWorker||!sweepState)return;const code=$('engine').textContent+'\n'+screeningMetrics.toString()+'\nonmessage=e=>{try{const r=solveModel(e.data);postMessage({status:"ok",metrics:screeningMetrics(r)});}catch(err){postMessage({status:"error",error:err.message});}};';const url=URL.createObjectURL(new Blob([code],{type:'application/javascript'}));try{sweepWorker=new Worker(url);}catch(e){screeningStatus('Worker could not start: '+e.message,true);return;}finally{URL.revokeObjectURL(url);}screeningBusy(true);screeningRender();screeningNext();}
function screeningNext(){const index=sweepState.rows.findIndex(r=>r===null);if(index<0){sweepWorker.terminate();sweepWorker=null;screeningBusy(false);screeningRender();screeningStatus('Complete | '+sweepState.rows.filter(r=>r.status==='ok').length+' solved / '+sweepState.rows.filter(r=>r.status==='error').length+' failed. Results retain the captured Model conditions.');return;}const activeWorker=sweepWorker,started=performance.now();const completed=sweepState.rows.filter(Boolean),seconds=completed.reduce((s,r)=>s+(r.elapsed||0),0),remaining=completed.length?seconds/completed.length*(sweepState.rows.length-completed.length):null;screeningStatus('Calculating '+(index+1)+' / '+sweepState.rows.length+' | '+sweepState.x.key+' = '+fmt(sweepState.xs[index%sweepState.xs.length])+' | '+sweepState.y.key+' = '+fmt(sweepState.ys[Math.floor(index/sweepState.xs.length)])+(remaining===null?'':' | estimated remaining '+fmt(remaining,0)+' s (completed-point average)'));
 const done=data=>{if(sweepWorker!==activeWorker)return;sweepState.rows[index]={...data,elapsed:(performance.now()-started)/1000};screeningPersist();screeningRender();screeningNext();};sweepWorker.onmessage=e=>done(e.data);sweepWorker.onerror=e=>{if(sweepWorker!==activeWorker)return;sweepWorker.terminate();sweepWorker=null;sweepState.rows[index]={status:'error',error:e.message||'Worker failed',elapsed:(performance.now()-started)/1000};screeningPersist();screeningBusy(false);screeningRender();screeningStatus('Worker failed. Completed points retained; Resume retries uncomputed points.',true);};sweepWorker.postMessage(sweepParameters(sweepState,index));}
function screeningStop(){if(!sweepWorker)return;sweepWorker.terminate();sweepWorker=null;screeningPersist();screeningBusy(false);screeningStatus('Stopped. Completed points retained; the interrupted point remains pending.');screeningRender();}
function screeningAxisLabel(a,s){if(a.key==='command')return 'Supply setpoint ('+({V:'V',I:'A',P:'W'}[s.base.mode])+')';if(a.key==='flowRate')return 'Gas flow ('+({mass:'kg/s',standard:'standard mL/min'}[s.base.flowUnit]||'actual mL/min')+')';return sweepFields.find(([k])=>k===a.key)?.[1]||a.key;}
function screeningRender(){sweepPlotBounds=null;if(!sweepState){mountFigure('sweepCanvas',null);return;}
 const state=sweepState,nx=state.xs.length,ny=state.ys.length,key=$('sweepOutput').value,values=state.rows.map(r=>r?.status==='ok'&&Number.isFinite(r.metrics?.[key])?r.metrics[key]:null),finite=values.filter(Number.isFinite),lo=finite.length?Math.min(...finite):0,hi=finite.length?Math.max(...finite):1;
 const f=Figure5.figure(Figure5.axis(state.xs[0],state.xs[nx-1],state.x.scale==='log'),Figure5.axis(state.ys[0],state.ys[ny-1],state.y.scale==='log'),figureLabel(screeningAxisLabel(state.x,state)),figureLabel(screeningAxisLabel(state.y,state)),{bar:true});
 const xp=state.xs.map(f.x),yp=state.ys.map(f.y),x=i=>{const n=Math.min(nx-2,Math.floor(i));return xp[n]+(xp[n+1]-xp[n])*(i-n);},y=j=>{const n=Math.min(ny-2,Math.floor(j));return yp[n]+(yp[n+1]-yp[n])*(j-n);};sweepPlotBounds={f,xp,yp};
 f.rect(x(0),y(ny-1),x(nx-1)-x(0),y(0)-y(ny-1),'#f2f2f2');for(let j=0;j<ny-1;j++)for(let i=0;i<nx-1;i++){const q=[values[j*nx+i],values[j*nx+i+1],values[(j+1)*nx+i+1],values[(j+1)*nx+i]];if(q.some(v=>!Number.isFinite(v)))continue;const n=12;for(let a=0;a<n;a++)for(let b=0;b<n;b++){const u=(a+.5)/n,v=(b+.5)/n,value=v<=u?q[0]*(1-u)+q[1]*(u-v)+q[2]*v:q[0]*(1-v)+q[2]*u+q[3]*(v-u);f.rect(x(i+a/n),y(j+(b+1)/n),x(i+(a+1)/n)-x(i+a/n)+.03,y(j+b/n)-y(j+(b+1)/n)+.03,Figure5.viridis(hi===lo?.5:(value-lo)/(hi-lo)));}}
 if($('sweepContours').checked&&hi>lo)for(let n=1;n<8;n++)for(const [a,b]of contourSegments(values,nx,ny,lo+(hi-lo)*n/8))f.line(x(a[0]),y(a[1]),x(b[0]),y(b[1]),'#444',.6);
 state.rows.forEach((r,i)=>{const xx=x(i%nx),yy=y(Math.floor(i/nx));if(r?.status==='error'){f.line(xx-3,yy-3,xx+3,yy+3,'#b32828',1.2);f.line(xx+3,yy-3,xx-3,yy+3,'#b32828',1.2);}else if(r?.metrics?.limiter&&r.metrics.limiter!=='Setpoint')f.rect(xx-3,yy-3,6,6,'#222');else f.dot(xx,yy,Number.isFinite(values[i])?Figure5.viridis(hi===lo?.5:(values[i]-lo)/(hi-lo)):'#aaa',5);});
 f.frame();if(finite.length){for(let i=0;i<160;i++)f.rect(365,f.B-260*(i+1)/160,12,260/160+.03,Figure5.viridis(i/159));for(let i=0;i<=(hi===lo?0:4);i++){const yy=hi===lo?(f.T+f.B)/2:f.B-260*i/4;f.line(377,yy,381,yy,'#222',.9);f.text(385,yy+5,Figure5.number(lo+(hi-lo)*i/4),15,'start');}f.text(463,150,figureLabel(sweepOutputs.find(([k])=>k===key)[1]),18,'middle',-90);}
 if(sweepSelected>=0)f.selection=[x(sweepSelected%nx),y(Math.floor(sweepSelected/nx))];mountFigure('sweepCanvas',f);
 $('sweepLevels').textContent=finite.length?(hi===lo?'Uniform output: '+fmt(lo):'Contour levels: '+Array.from({length:7},(_,i)=>fmt(lo+(hi-lo)*(i+1)/8,4)).join(' | ')):'No finite values for this output yet.';
 const completed=state.rows.filter(Boolean).length;$('sweepProgress').max=state.rows.length;$('sweepProgress').value=completed;$('sweepSummary').textContent=completed+' / '+state.rows.length+' points | '+finite.length+' valid values for this output | captured '+new Date(state.created).toLocaleString()+' | '+state.base.study+' | '+state.base.mode+' control';$('sweepCsv').disabled=false;$('sweepJson').disabled=false;$('sweepResume').disabled=!!sweepWorker||completed===state.rows.length;
 const failures=state.rows.map((r,i)=>r?.status==='error'?'('+fmt(state.xs[i%nx])+', '+fmt(state.ys[Math.floor(i/nx)])+'): '+r.error:null).filter(Boolean);$('sweepErrors').textContent=failures.join('\n')||'No failed points.';screeningInspect();}
function screeningInspect(){if(!sweepState||sweepSelected<0){$('sweepPoint').textContent='Click a calculated point to inspect it.';$('sweepLoad').disabled=true;return;}const s=sweepState,r=s.rows[sweepSelected],v=r?.metrics?.[$('sweepOutput').value];$('sweepPoint').textContent=s.x.key+' = '+fmt(s.xs[sweepSelected%s.xs.length])+' | '+s.y.key+' = '+fmt(s.ys[Math.floor(sweepSelected/s.xs.length)])+' | '+(r?.status==='error'?r.error:r?.status==='ok'?$('sweepOutput').selectedOptions[0].textContent+': '+fmt(v)+' | '+r.metrics.limiter+' | '+fmt(r.elapsed,2)+' s | mesh '+r.metrics.nx+'×'+r.metrics.ny+'×'+r.metrics.nz:'Pending');$('sweepLoad').disabled=!!sweepWorker||!r||r.status!=='ok';}
for(const prefix of ['sweepX','sweepY'])for(const [key,label]of sweepFields){const o=document.createElement('option');o.value=key;o.textContent=label;$(prefix+'Param').append(o);}for(const [key,label]of sweepOutputs){const o=document.createElement('option');o.value=key;o.textContent=label;$('sweepOutput').append(o);}$('sweepXParam').value='command';$('sweepYParam').value='flowRate';
$('sweepStart').onclick=screeningStart;$('sweepStop').onclick=screeningStop;$('sweepResume').onclick=screeningLaunch;$('sweepOutput').onchange=screeningRender;$('sweepContours').onchange=screeningRender;
$('sweepCanvas').onclick=e=>{if(!sweepPlotBounds)return;const {f,xp,yp}=sweepPlotBounds,b=$('sweepCanvas').getBoundingClientRect(),xx=(e.clientX-b.left)*f.width/b.width,yy=(e.clientY-b.top)*f.height/b.height;if(xx<f.L-5||xx>f.R+5||yy<f.T-5||yy>f.B+5)return;const nearest=(a,v)=>a.reduce((best,n,i)=>Math.abs(n-v)<Math.abs(a[best]-v)?i:best,0);sweepSelected=nearest(yp,yy)*xp.length+nearest(xp,xx);screeningRender();};
$('sweepLoad').onclick=()=>{if(!sweepState||sweepSelected<0||sweepWorker||worker)return;try{loadParameters(sweepParameters(sweepState,sweepSelected));$('worktab').click();}catch(e){screeningStatus(e.message,true);}};
$('sweepJson').onclick=()=>{if(sweepState)download('joule3d-screening.json',JSON.stringify(sweepState,null,2),'application/json');};
$('sweepCsv').onclick=()=>{if(!sweepState)return;const s=sweepState,quote=v=>'"'+String(v??'').replace(/"/g,'""')+'"',headers=['x_parameter','x_label','x_value','y_parameter','y_label','y_value','study','control_mode','flow_unit','status','error','elapsed_s',...sweepOutputs.map(([k])=>k),'nx','ny','nz','limiter'],lines=[headers.map(quote).join(',')];s.rows.forEach((r,i)=>lines.push([s.x.key,screeningAxisLabel(s.x,s),s.xs[i%s.xs.length],s.y.key,screeningAxisLabel(s.y,s),s.ys[Math.floor(i/s.xs.length)],s.base.study,s.base.mode,s.base.flowUnit||'actual',r?.status||'pending',r?.error||'',r?.elapsed,...sweepOutputs.map(([k])=>r?.metrics?.[k]),r?.metrics?.nx,r?.metrics?.ny,r?.metrics?.nz,r?.metrics?.limiter].map(quote).join(',')));download('joule3d-screening.csv',lines.join('\n'),'text/csv');};
function screeningRestore(s){if(s?.schema!=='joule3d-screening-1'||!s.base||!s.x||!s.y||s.x.key===s.y.key||![s.x.key,s.y.key].every(k=>sweepFields.some(([v])=>v===k)))throw Error('Unsupported sweep file.');const xs=sweepValues(s.x.min,s.x.max,s.x.count,s.x.scale),ys=sweepValues(s.y.min,s.y.max,s.y.count,s.y.scale);if(xs.length*ys.length>400||!Array.isArray(s.rows)||s.rows.length!==xs.length*ys.length||s.rows.some(r=>r!==null&&(!r||!['ok','error'].includes(r.status)||r.status==='ok'&&!r.metrics)))throw Error('Malformed sweep results.');sweepState={...s,xs,ys};sweepSelected=-1;for(const [prefix,a]of [['sweepX',s.x],['sweepY',s.y]]){for(const [suffix,k]of [['Param','key'],['Min','min'],['Max','max'],['Count','count'],['Scale','scale']])$(prefix+suffix).value=a[k];}screeningBusy(false);screeningRender();screeningStatus('Restored captured run. Resume calculates pending points using its original Model settings.');}
$('sweepRestore').onclick=()=>{if(sweepWorker||worker)return;try{const s=JSON.parse(localStorage.getItem('joule3d.screening.v1')||'null');screeningRestore(s);}catch(e){screeningStatus(e.message,true);}};
$('sweepImport').onchange=async e=>{if(sweepWorker||worker)return;try{const f=e.target.files[0];if(!f)return;if(f.size>16e6)throw Error('Sweep file exceeds 16 MB.');screeningRestore(JSON.parse(await f.text()));screeningPersist();}catch(err){screeningStatus(err.message,true);}finally{e.target.value='';}};
new ResizeObserver(()=>{if(!$('screening').hidden)screeningRender();}).observe($('sweepCanvas'));

initFigureExports();
