/* Pure screening utilities, shared by UI and numerical checks. */
function sweepValues(lo,hi,count,scale){
 if(!Number.isFinite(lo)||!Number.isFinite(hi)||!(hi>lo)||!Number.isInteger(count)||count<2||count>30)throw Error('Each axis needs finite min < max and 2–30 points.');
 if(!['linear','log'].includes(scale))throw Error('Unknown axis spacing.');if(scale==='log'&&lo<=0)throw Error('Logarithmic axes require positive values.');
 return Array.from({length:count},(_,i)=>i===count-1?hi:scale==='log'?Math.exp(Math.log(lo)+(Math.log(hi)-Math.log(lo))*i/(count-1)):lo+(hi-lo)*i/(count-1));
}
function sweepParameters(state,index){const p=structuredClone(state.base);p[state.x.key]=state.xs[index%state.xs.length];p[state.y.key]=state.ys[Math.floor(index/state.xs.length)];return p;}
function screeningMetrics(r){const s=r.stats,w=r.wall;return {heaterMax:s.heaterMax,max:s.max,min:s.min,spread:s.spread,avg:s.avg,wallMax:w?.stats?.max??(w?.inner?Math.max(...w.inner,...w.outer):null),electrodeMax:s.electrodeMax,outlet:r.gas?.stats.outlet??null,dp:r.gas?.stats.dp??null,Re:r.gas?.stats.Re??null,R:s.R,V:s.V,I:s.I,P:s.P,contactPower:s.contactPower,peakJ:s.peakJ,targetPercent:s.targetFraction*100,rate:s.rate,seconds:s.seconds,energyPercent:s.energyError*100,massPercent:r.gas?r.gas.stats.massError*100:null,inputEnergy:s.inputEnergy,stored:s.stored,integratedPercent:s.integratedError===null?null:s.integratedError*100,nx:r.mesh.nx,ny:r.mesh.ny,nz:r.mesh.nz,limiter:s.limiter};}
function contourSegments(values,nx,ny,level){const lines=[];for(let j=0;j<ny-1;j++)for(let i=0;i<nx-1;i++){const ids=[j*nx+i,j*nx+i+1,(j+1)*nx+i+1,(j+1)*nx+i];if(ids.some(k=>!Number.isFinite(values[k])))continue;const pts=[[i,j],[i+1,j],[i+1,j+1],[i,j+1]];for(const tri of [[0,1,2],[0,2,3]]){const cuts=[];for(let e=0;e<3;e++){const a=tri[e],b=tri[(e+1)%3],va=values[ids[a]],vb=values[ids[b]];if((va<level&&vb>=level)||(vb<level&&va>=level)){const t=(level-va)/(vb-va);cuts.push([pts[a][0]+t*(pts[b][0]-pts[a][0]),pts[a][1]+t*(pts[b][1]-pts[a][1])]);}}if(cuts.length===2)lines.push(cuts);}}return lines;}
if(typeof module!=='undefined')module.exports={sweepValues,sweepParameters,screeningMetrics,contourSegments};
